"""
Deterministic quantitative risk tools.

These are invoked by the orchestrator as *tools*, not generated by the LLM
(Section IV.C: "Quantitative agent ... so that numerical claims are computed,
not generated"). Two classical models are implemented:

  - Merton (1974) structural distance-to-default / probability of default.
  - Parametric (variance-covariance) Value-at-Risk.

Both are standard, closed-form, well-documented models; this module contains
no proprietary logic and is meant to be replaced with your firm's validated
model library in a production deployment.
"""

from __future__ import annotations

from dataclasses import dataclass
from math import log, sqrt

from scipy.stats import norm

from .data_models import QuantResult


@dataclass
class MertonInputs:
    asset_value: float          # V: market value of firm assets
    debt_face_value: float      # D: face value of debt (default point), typically due in T years
    asset_volatility: float     # sigma_V: annualized volatility of asset value
    risk_free_rate: float       # r
    horizon_years: float = 1.0  # T


def merton_distance_to_default(inputs: MertonInputs) -> QuantResult:
    """Merton (1974) structural credit risk model.

    d2 = [ln(V/D) + (r - 0.5*sigma_V^2) * T] / (sigma_V * sqrt(T))
    Distance-to-default = d2
    Risk-neutral probability of default = N(-d2)
    """
    V, D, sigma_V, r, T = (
        inputs.asset_value,
        inputs.debt_face_value,
        inputs.asset_volatility,
        inputs.risk_free_rate,
        inputs.horizon_years,
    )
    if V <= 0 or D <= 0 or sigma_V <= 0 or T <= 0:
        raise ValueError("Merton model inputs must be strictly positive.")

    d2 = (log(V / D) + (r - 0.5 * sigma_V ** 2) * T) / (sigma_V * sqrt(T))
    pd = float(norm.cdf(-d2))

    narrative = (
        f"Merton distance-to-default = {d2:.2f} standard deviations "
        f"(risk-neutral P[default within {T:g}y] \u2248 {pd:.2%}), "
        f"given assets={V:,.1f}, debt={D:,.1f}, asset vol={sigma_V:.1%}, r={r:.1%}."
    )
    return QuantResult(
        tool="merton_distance_to_default",
        inputs={"asset_value": V, "debt_face_value": D, "asset_volatility": sigma_V, "risk_free_rate": r, "horizon_years": T},
        outputs={"distance_to_default": d2, "probability_of_default": pd},
        narrative=narrative,
    )


def parametric_var(
    portfolio_value: float,
    expected_return: float,
    volatility: float,
    confidence: float = 0.99,
    horizon_days: int = 1,
) -> QuantResult:
    """Parametric (variance-covariance) Value-at-Risk over `horizon_days`,
    scaling volatility by sqrt(time) under the usual i.i.d.-returns
    assumption."""
    if not (0 < confidence < 1):
        raise ValueError("confidence must be in (0, 1)")

    z = float(norm.ppf(1 - confidence))
    horizon_vol = volatility * sqrt(horizon_days)
    var_return = expected_return * horizon_days + z * horizon_vol
    var_amount = -var_return * portfolio_value  # loss is positive when var_return < 0

    narrative = (
        f"{confidence:.0%} {horizon_days}-day parametric VaR \u2248 {var_amount:,.1f} "
        f"on a {portfolio_value:,.1f} position (ann. vol={volatility:.1%})."
    )
    return QuantResult(
        tool="parametric_var",
        inputs={
            "portfolio_value": portfolio_value,
            "expected_return": expected_return,
            "volatility": volatility,
            "confidence": confidence,
            "horizon_days": horizon_days,
        },
        outputs={"var_amount": var_amount},
        narrative=narrative,
    )


class QuantitativeAgent:
    """Dispatches a SubTask.quant_spec to the appropriate deterministic tool."""

    def run(self, quant_spec: dict) -> QuantResult:
        tool = quant_spec.get("tool")
        params = quant_spec.get("params", {})
        if tool == "merton_distance_to_default":
            return merton_distance_to_default(MertonInputs(**params))
        if tool == "parametric_var":
            return parametric_var(**params)
        raise ValueError(f"Unknown quant tool '{tool}'")
